# Copyright (c) 2026 Garrett Kinman
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

## C packaging.
##
## The generated model is a Nim module, which is fine if the firmware is Nim
## and useless otherwise. Most of the places this compiler is aimed at are
## someone else's C project — Keil, IAR, CubeIDE, Zephyr — where the model has
## to arrive as a `.a` and a header, with no Nim anywhere in the build.
##
## So this module writes two more files:
##
##   <stem>_api.nim   `{.exportc, cdecl.}` wrappers, built with --app:staticlib
##   <stem>.h         the header a C caller includes, and nothing else
##
## The header carries the numbers a caller actually needs — element counts,
## shapes, and for an affine model the scale and zero point of every input and
## output, because a C caller holding floats has to quantize them and the
## alternative is that they guess. All of it is `#define`d, so it is available
## to the preprocessor for static assertions and array sizing.
##
## Note what is *not* in the API: no allocation, no context handle, no session
## object. The arena is a static array inside the library, so there is nothing
## to pass around and nothing to free. One model, one set of functions.

import std/[strformat, strutils, os]
import ./ir, ./arena
# One version string for everything a build emits, so a header and the module
# beside it can never claim different provenance.
from ./emit import ToolVersion, cIdent

type CApiError* = object of CatchableError

func defaultPrefix*(g: Graph): string =
  &"steady_{cIdent(g.name)}_"

proc shapeList(shape: seq[int]): string =
  var parts: seq[string]
  for d in shape: parts.add $d
  parts.join(", ")

proc emitCApi*(g: Graph, p: Plan, outDir, stem: string, prefix = "") =
  ## Writes <stem>_api.nim and <stem>.h into `outDir`, alongside the output of
  ## `emitModel`. `prefix` defaults to `steady_<model>_`.
  if g.inputs.len == 0 or g.outputs.len == 0:
    raise newException(CApiError,
      &"model '{g.name}' has {g.inputs.len} inputs and {g.outputs.len} " &
      "outputs; a C API needs at least one of each")
  createDir(outDir)
  let pfx = if prefix.len > 0: prefix else: g.defaultPrefix
  let guard = "STEADY_" & cIdent(stem).toUpperAscii & "_H"
  # `cIdent` strips a trailing underscore, since an identifier may not end in
  # one — but a macro *prefix* needs its separator back.
  let macroPfx = cIdent(pfx).toUpperAscii & "_"

  # ---- the Nim shim -------------------------------------------------------
  var api = &"""
# Generated by steadyc {ToolVersion}. Do not edit.
#
# C entry points for '{g.name}'. Build as a static library:
#
#   nim c --app:staticlib --os:any --mm:none --panics:on --noMain \
#         -d:danger --path:<steady>/src {stem}_api.nim
#
# then link the resulting library and the companion {stem}_weights.c object
# into a C project and include {stem}.h.

import ./{stem}

# Nim's generated entry point. It initialises module-level state; there is no
# heap and no GC to start, so for this library it is close to a no-op — but
# calling it once is the contract, and doing it from `init` means a C caller
# never has to know the name.
proc NimMain() {{.importc, cdecl.}}

var ready = false

proc {pfx}init() {{.exportc: "{pfx}init", cdecl.}} =
  if not ready:
    NimMain()
    ready = true

proc {pfx}invoke() {{.exportc: "{pfx}invoke", cdecl.}} =
  {stem}.invoke()

proc {pfx}arena_size(): csize_t {{.exportc: "{pfx}arena_size", cdecl.}} =
  csize_t({stem}.ArenaSize)
"""
  for i, t in g.inputs:
    let tt = g.tensors[t]
    api.add &"""

proc {pfx}input{i}(): ptr {tt.dtype.nimTypeName} {{.exportc: "{pfx}input{i}", cdecl.}} =
  ## '{tt.name}', shape {tt.shape}, {tt.numElements} elements
  cast[ptr {tt.dtype.nimTypeName}]({stem}.input{i}())
"""
  for i, t in g.outputs:
    let tt = g.tensors[t]
    api.add &"""

proc {pfx}output{i}(): ptr {tt.dtype.nimTypeName} {{.exportc: "{pfx}output{i}", cdecl.}} =
  ## '{tt.name}', shape {tt.shape}, {tt.numElements} elements
  cast[ptr {tt.dtype.nimTypeName}]({stem}.output{i}())
"""

  # ---- the header ---------------------------------------------------------
  var hdr = &"""
/* Generated by steadyc {ToolVersion}. Do not edit.
 *
 * Model '{g.name}', numeric policy {g.policy.policyName}.
 *
 *   peak arena       {p.arenaSize} bytes, statically allocated in the library
 *   flash constants  {g.totalConstBytes} bytes
 *
 * Usage:
 *
 *   {pfx}init();
 *   {g.tensors[g.inputs[0]].dtype.cTypeName} *in = {pfx}input0();
 *   for (size_t i = 0; i < {macroPfx}INPUT0_ELEMS; i++) in[i] = ...;
 *   {pfx}invoke();
 *   const {g.tensors[g.outputs[0]].dtype.cTypeName} *out = {pfx}output0();
 *
 * There is no context handle and nothing to free: the arena is a static
 * array inside the library. `invoke` is not reentrant and carries no state
 * between calls.
 *
 * Buffer lifetimes, which matter because the arena is packed:
 *
 *   - An input buffer is scratch space. Once the model has read it, the
 *     planner is free to reuse those bytes for an activation, so its contents
 *     after `invoke` are undefined. Refill every input before every invoke;
 *     do not treat it as storage that persists.
 *   - An output buffer stays valid until the next `invoke`.
 *   - The pointers themselves never move. They are fixed offsets into a
 *     static array, so caching them is fine.
 */
#ifndef {guard}
#define {guard}

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {{
#endif

#define {macroPfx}MODEL_NAME    "{g.name}"
#define {macroPfx}TOOL_VERSION  "{ToolVersion}"
#define {macroPfx}POLICY        "{g.policy.policyName}"
#define {macroPfx}ARENA_SIZE    {p.arenaSize}
#define {macroPfx}NUM_INPUTS    {g.inputs.len}
#define {macroPfx}NUM_OUTPUTS   {g.outputs.len}

"""
  proc tensorMacros(role: string, i: int, t: Tensor): string =
    let tag = &"{macroPfx}{role}{i}_"
    result = &"/* '{t.name}' */\n"
    result.add &"#define {tag}ELEMS  {t.numElements}\n"
    result.add &"#define {tag}RANK   {t.shape.len}\n"
    result.add &"#define {tag}SHAPE  {{ {shapeList(t.shape)} }}\n"
    result.add &"#define {tag}BYTES  {t.byteSize}\n"
    if t.quant.scales.len > 0:
      # A caller with real values needs these to get into and out of the
      # quantized domain: q = round(x / SCALE) + ZERO_POINT.
      result.add &"#define {tag}SCALE       {t.quant.scales[0]:.9e}f\n"
      let zero = if t.quant.zeroPoints.len > 0: t.quant.zeroPoints[0] else: 0'i32
      result.add &"#define {tag}ZERO_POINT  ({zero})\n"

  for i, t in g.inputs:
    hdr.add tensorMacros("INPUT", i, g.tensors[t])
    hdr.add "\n"
  for i, t in g.outputs:
    hdr.add tensorMacros("OUTPUT", i, g.tensors[t])
    hdr.add "\n"

  hdr.add &"""/* Call once before the first invoke. */
void {pfx}init(void);

/* Run the model over whatever is currently in the input buffers. */
void {pfx}invoke(void);

/* Bytes of statically allocated activation arena. */
size_t {pfx}arena_size(void);

"""
  for i, t in g.inputs:
    hdr.add &"{g.tensors[t].dtype.cTypeName} *{pfx}input{i}(void);\n"
  for i, t in g.outputs:
    hdr.add &"{g.tensors[t].dtype.cTypeName} *{pfx}output{i}(void);\n"

  hdr.add """
#ifdef __cplusplus
}
#endif
#endif
"""

  writeFile(outDir / (stem & "_api.nim"), api)
  writeFile(outDir / (stem & ".h"), hdr)
