# Copyright (c) 2026 Garrett Kinman
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

## Code emission.
##
## Produces three files per model:
##
##   <name>_weights.h   extern declarations
##   <name>_weights.c   const arrays — weights, folded biases, requant tables
##   <name>.nim         arena, accessors, and a straight-line `invoke`
##
## Weights are emitted as C rather than as Nim `const` deliberately. A Nim
## `const` cannot have its address taken, and a module-level `let` lands in
## `.data` — that is, it gets copied into RAM at startup, which on a part
## with 64 KB of SRAM and 512 KB of flash is precisely backwards. Emitting
## `const` C arrays puts them in `.rodata`, keeps them in flash, gives
## explicit control over alignment and section placement, and keeps the Nim
## compiler from having to parse megabytes of array literals.
##
## `invoke` contains no dispatch, no op table, and no interpreter — just the
## calls, in order, with every buffer address resolved to a constant offset.

import std/[strformat, strutils, tables, times, os]
import ./ir, ./quant, ./arena

const ToolVersion* = "0.1.0"

type EmitError* = object of CatchableError

func sanitize(s: string): string =
  for c in s:
    if c in {'a'..'z', 'A'..'Z', '0'..'9'}: result.add c
    else: result.add '_'
  if result.len > 0 and result[0] in {'0'..'9'}:
    result = "t" & result

func cSym(g: Graph, prefix, name: string): string =
  &"steady_{sanitize(g.name)}_{prefix}{sanitize(name)}"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# C LITERAL FORMATTING
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

proc f32Literal(x: float32): string =
  ## Nine significant digits round-trips float32 exactly, so the constant in
  ## flash is bit-identical to the one the host validated against.
  if x != x: return "(0.0f/0.0f)"
  if x == Inf.float32: return "(1.0f/0.0f)"
  if x == NegInf.float32: return "(-1.0f/0.0f)"
  result = formatFloat(float(x), ffScientific, 9) & "f"

proc emitArrayBody(s: var string, t: Tensor, data: seq[byte]) =
  const PerLine = 12
  case t.dtype
  of dtInt8:
    for i in 0 ..< t.numElements:
      if i mod PerLine == 0: s.add "\n  "
      s.add $cast[int8](data[i]) & ","
  of dtFp8:
    for i in 0 ..< t.numElements:
      if i mod PerLine == 0: s.add "\n  "
      s.add "0x" & toHex(data[i], 2) & "u,"
  of dtInt32:
    for i in 0 ..< t.numElements:
      if i mod 8 == 0: s.add "\n  "
      var v: int32
      copyMem(addr v, unsafeAddr data[i * 4], 4)
      s.add $v & ","
  of dtFloat32:
    for i in 0 ..< t.numElements:
      if i mod 6 == 0: s.add "\n  "
      var v: float32
      copyMem(addr v, unsafeAddr data[i * 4], 4)
      s.add f32Literal(v) & ","
  s.add "\n"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# WEIGHTS FILES
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

type ConstBlob = object
  sym: string
  dtype: DType
  count: int
  body: string

proc emitWeightsFiles(g: Graph, blobs: seq[ConstBlob], stem: string,
                      hdr, src: var string) =
  let guard = "STEADY_" & sanitize(stem).toUpperAscii & "_WEIGHTS_H"
  hdr = &"""
/* Generated by steadyc {ToolVersion}. Do not edit. */
#ifndef {guard}
#define {guard}

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

"""
  for b in blobs:
    hdr.add &"extern const {b.dtype.cTypeName} {b.sym}[{b.count}];\n"
  hdr.add """
#ifdef __cplusplus
}
#endif
#endif
"""

  src = &"""
/* Generated by steadyc {ToolVersion}. Do not edit. */
#include "{stem}_weights.h"

/* Alignment keeps word loads legal on strict-alignment cores and keeps DMA
   engines happy. Override STEADY_SECTION to relocate weights into external
   flash. */
#if defined(__GNUC__) || defined(__clang__)
#  define STEADY_ALIGN(n) __attribute__((aligned(n)))
#elif defined(_MSC_VER)
#  define STEADY_ALIGN(n) __declspec(align(n))
#else
#  define STEADY_ALIGN(n)
#endif

#ifndef STEADY_SECTION
#  define STEADY_SECTION
#endif

"""
  for b in blobs:
    src.add &"STEADY_SECTION const {b.dtype.cTypeName} {b.sym}[{b.count}] STEADY_ALIGN(8) = {{"
    src.add b.body
    src.add "};\n\n"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# PARAMS
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

proc paramsExpr(g: Graph, rp: ResolvedParams, multSym, shiftSym: string,
                perChannel: bool): string =
  if rp.affine:
    let stride = if perChannel: 1 else: 0
    &"AffineParams(mult: cast[ptr UncheckedArray[int32]](addr {multSym}), " &
    &"shift: cast[ptr UncheckedArray[int32]](addr {shiftSym}), " &
    &"channelStride: {stride}, outZeroPoint: {rp.outZeroPoint}'i32, " &
    &"actMin: {rp.qActMin}'i32, actMax: {rp.qActMax}'i32)"
  else:
    let lo = if rp.fActMin == NegInf.float32: "-Inf.float32" else: &"{rp.fActMin}'f32"
    let hi = if rp.fActMax == Inf.float32: "Inf.float32" else: &"{rp.fActMax}'f32"
    &"RealParams[float32](actMin: {lo}, actMax: {hi})"

proc storeLiteral(p: PolicyKind, v: int32): string =
  ## A Store-typed literal for clamp bounds and pad values.
  case p
  of pkAffineI8: &"{v}'i8"
  of pkRealF32: &"{float32(v)}'f32"
  of pkRealFp8: &"toFp8({float32(v)}'f32)"

proc clampLiteral(p: PolicyKind, fused: FusedAct, outQ: Quant): (string, string) =
  case p
  of pkAffineI8:
    let (lo, hi) = affineActRange(fused, outQ)
    (&"{lo}'i8", &"{hi}'i8")
  of pkRealF32:
    let (lo, hi) = realActRange(fused)
    ((if lo == NegInf.float32: "-Inf.float32" else: &"{lo}'f32"),
     (if hi == Inf.float32: "Inf.float32" else: &"{hi}'f32"))
  of pkRealFp8:
    let (lo, hi) = realActRange(fused)
    ((if lo == NegInf.float32: "Fp8Min" else: &"toFp8({lo}'f32)"),
     (if hi == Inf.float32: "Fp8Max" else: &"toFp8({hi}'f32)"))

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# MAIN EMITTER
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

proc emitModel*(g: Graph, p: Plan, outDir, stem: string, sourceHash = "") =
  ## Writes <stem>.nim, <stem>_weights.c and <stem>_weights.h into `outDir`.
  createDir(outDir)
  let alias = resolveAliases(g)
  let policy = g.policy.policyName
  let storeDt = g.policy.storeType
  let storeNim = storeDt.nimTypeName

  var blobs: seq[ConstBlob]
  var nimSrc = ""

  proc addBlob(sym: string, t: Tensor, data: seq[byte]): string =
    var body = ""
    var tt = t
    emitArrayBody(body, tt, data)
    blobs.add ConstBlob(sym: sym, dtype: t.dtype, count: t.numElements, body: body)
    sym

  proc addI32Blob(sym: string, xs: seq[int32]): string =
    var body = ""
    for i, v in xs:
      if i mod 8 == 0: body.add "\n  "
      body.add $v & ","
    body.add "\n"
    blobs.add ConstBlob(sym: sym, dtype: dtInt32, count: xs.len, body: body)
    sym

  # ---- header -------------------------------------------------------------
  nimSrc.add &"""
# Generated by steadyc {ToolVersion} on {now().format("yyyy-MM-dd HH:mm:ss")}.
# Model: {g.name}   policy: {policy}
"""
  if sourceHash.len > 0:
    nimSrc.add &"# Source model hash: {sourceHash}\n"
  nimSrc.add &"""#
# DO NOT EDIT. Regenerate with steadyc.
#
# Peak arena: {p.arenaSize} bytes    Flash constants: {g.totalConstBytes} bytes

import steady/kernels/dispatch

{{.compile: "{stem}_weights.c".}}

const
  ArenaSize* = {p.arenaSize}
  ModelName* = "{g.name}"
  ToolVersion* = "{ToolVersion}"
"""
  if sourceHash.len > 0:
    nimSrc.add &"  SourceHash* = \"{sourceHash}\"\n"

  # ---- constants ----------------------------------------------------------
  var declBlock = ""
  var opCalls = ""

  # Extern declarations are emitted straight into the generated C rather than
  # pulled in via the header. The header exists for people integrating from
  # C; making Nim depend on it would mean depending on an include path that
  # varies with how the project is built.
  var externBlock = ""

  proc declConst(sym: string, t: Tensor) =
    externBlock.add &"extern const {t.dtype.cTypeName} {sym}[{t.numElements}];\n"
    declBlock.add &"  {sym} {{.importc, nodecl.}}: array[{t.numElements}, " &
                  &"{t.dtype.nimTypeName}]\n"

  proc declI32Const(sym: string, n: int) =
    externBlock.add &"extern const int32_t {sym}[{n}];\n"
    declBlock.add &"  {sym} {{.importc, nodecl.}}: array[{n}, int32]\n"

  # Weight and bias tensors, with zero-point correction folded into biases.
  var constSym = initTable[int, string]()
  for oi, op in g.ops:
    if op.kind in {okFullyConnected, okConv2d, okDepthwiseConv2d}:
      let wIdx = op.inputs[1]
      let bIdx = op.inputs[2]
      if wIdx notin constSym:
        let sym = cSym(g, "w_", g.tensors[wIdx].name)
        discard addBlob(sym, g.tensors[wIdx], g.tensors[wIdx].data)
        declConst(sym, g.tensors[wIdx])
        constSym[wIdx] = sym
      if bIdx notin constSym:
        let sym = cSym(g, "b_", g.tensors[bIdx].name)
        let folded = foldBias(g, op)
        discard addBlob(sym, g.tensors[bIdx], folded)
        declConst(sym, g.tensors[bIdx])
        constSym[bIdx] = sym

  # ---- op calls -----------------------------------------------------------
  proc bufExpr(t: int): string =
    let tt = g.tensors[t]
    let off = p.offsetFor(g, alias, t)
    &"A({off}, {tt.dtype.nimTypeName})"

  proc constExpr(t: int): string =
    &"cast[ptr UncheckedArray[{g.tensors[t].dtype.nimTypeName}]](addr {constSym[t]})"

  for oi, op in g.ops:
    if op.isPureAlias:
      opCalls.add &"  # op{oi} '{op.name}': reshape — aliased, no code emitted\n"
      continue

    opCalls.add &"  # op{oi} '{op.name}' ({op.kind})\n"
    let y = op.outputs[0]

    case op.kind
    of okFullyConnected, okConv2d, okDepthwiseConv2d:
      let x = op.inputs[0]
      let w = op.inputs[1]
      let b = op.inputs[2]
      let wT = g.tensors[w]
      let outC =
        if op.kind == okFullyConnected: wT.shape[0]
        elif op.kind == okConv2d: wT.shape[0]
        else: wT.shape[3]
      let rp = resolveMatmulParams(g, g.tensors[x], wT, g.tensors[y],
                                   op.fused, outC)
      var multSym, shiftSym: string
      if rp.affine:
        multSym = addI32Blob(cSym(g, &"m{oi}_", op.name), rp.mult)
        shiftSym = addI32Blob(cSym(g, &"s{oi}_", op.name), rp.shift)
        declI32Const(multSym, rp.mult.len)
        declI32Const(shiftSym, rp.shift.len)
      let prm = paramsExpr(g, rp, multSym, shiftSym, wT.quant.isPerChannel)
      let pv = storeLiteral(g.policy, padValueFor(g, g.tensors[x]))

      case op.kind
      of okFullyConnected:
        opCalls.add &"  fullyConnected({policy}, {bufExpr(y)}, {bufExpr(x)}, " &
                    &"{constExpr(w)}, {constExpr(b)},\n    {prm}, " &
                    &"{wT.shape[0]}, {wT.shape[1]})\n"
      of okConv2d:
        let xs = g.tensors[x].shape
        let ys = g.tensors[y].shape
        opCalls.add &"  conv2d({policy}, {bufExpr(y)}, {bufExpr(x)}, " &
                    &"{constExpr(w)}, {constExpr(b)},\n    {prm},\n" &
                    &"    {xs[1]}, {xs[2]}, {xs[3]}, {ys[1]}, {ys[2]}, {ys[3]}, " &
                    &"{op.kH}, {op.kW}, {op.strideH}, {op.strideW}, " &
                    &"{op.padTop}, {op.padLeft}, {op.dilationH}, {op.dilationW}, {pv})\n"
      of okDepthwiseConv2d:
        let xs = g.tensors[x].shape
        let ys = g.tensors[y].shape
        opCalls.add &"  depthwiseConv2d({policy}, {bufExpr(y)}, {bufExpr(x)}, " &
                    &"{constExpr(w)}, {constExpr(b)},\n    {prm},\n" &
                    &"    {xs[1]}, {xs[2]}, {xs[3]}, {ys[1]}, {ys[2]}, " &
                    &"{op.kH}, {op.kW}, {op.depthMultiplier}, " &
                    &"{op.strideH}, {op.strideW}, {op.padTop}, {op.padLeft}, " &
                    &"{op.dilationH}, {op.dilationW}, {pv})\n"
      else: discard

    of okMaxPool2d, okAvgPool2d:
      let x = op.inputs[0]
      let xs = g.tensors[x].shape
      let ys = g.tensors[y].shape
      let (lo, hi) = clampLiteral(g.policy, op.fused, g.tensors[y].quant)
      let fn = if op.kind == okMaxPool2d: "maxPool2d" else: "avgPool2d"
      opCalls.add &"  {fn}({policy}, {bufExpr(y)}, {bufExpr(x)},\n" &
                  &"    {xs[1]}, {xs[2]}, {xs[3]}, {ys[1]}, {ys[2]}, " &
                  &"{op.kH}, {op.kW}, {op.strideH}, {op.strideW}, " &
                  &"{op.padTop}, {op.padLeft}, {lo}, {hi})\n"

    of okAdd:
      let a = op.inputs[0]
      let b = op.inputs[1]
      let (rp, rescale) = resolveAddParams(g, g.tensors[a], g.tensors[b],
                                           g.tensors[y], op.fused)
      var multSym, shiftSym: string
      if rp.affine:
        multSym = addI32Blob(cSym(g, &"m{oi}_", op.name), rp.mult)
        shiftSym = addI32Blob(cSym(g, &"s{oi}_", op.name), rp.shift)
        declI32Const(multSym, rp.mult.len)
        declI32Const(shiftSym, rp.shift.len)
      let prm = paramsExpr(g, rp, multSym, shiftSym, false)
      opCalls.add &"  addElementwise({policy}, {bufExpr(y)}, {bufExpr(a)}, " &
                  &"{bufExpr(b)},\n    {prm}, {g.tensors[y].numElements},\n" &
                  &"    {rescale.aMult}'i32, {rescale.aShift}'i32, " &
                  &"{rescale.bMult}'i32, {rescale.bShift}'i32, " &
                  &"{rescale.aOffset}'i32, {rescale.bOffset}'i32)\n"

    of okClamp:
      let x = op.inputs[0]
      let (lo, hi) = clampLiteral(g.policy, op.fused, g.tensors[y].quant)
      opCalls.add &"  clamp1d({policy}, {bufExpr(y)}, {bufExpr(x)}, " &
                  &"{g.tensors[y].numElements}, {lo}, {hi})\n"

    of okReshape:
      discard

  # ---- assemble -----------------------------------------------------------
  if declBlock.len > 0:
    nimSrc.add "\n# Flash-resident constants, defined in the companion C file.\n"
    nimSrc.add "{.emit: \"\"\"/*TYPESECTION*/\n#include <stdint.h>\n"
    nimSrc.add externBlock
    nimSrc.add "\"\"\".}\n\nlet\n"
    nimSrc.add declBlock

  nimSrc.add &"""

var arena {{.align(8).}}: array[ArenaSize, byte]

template A(off: int, T: typedesc): ptr UncheckedArray[T] =
  cast[ptr UncheckedArray[T]](addr arena[off])

"""

  for i, t in g.inputs:
    let tt = g.tensors[t]
    nimSrc.add &"proc input{i}*(): ptr UncheckedArray[{tt.dtype.nimTypeName}] " &
               &"{{.inline.}} =\n" &
               &"  ## '{tt.name}', shape {tt.shape}, {tt.numElements} elements\n" &
               &"  {bufExpr(t)}\n\n"
  for i, t in g.outputs:
    let tt = g.tensors[t]
    nimSrc.add &"proc output{i}*(): ptr UncheckedArray[{tt.dtype.nimTypeName}] " &
               &"{{.inline.}} =\n" &
               &"  ## '{tt.name}', shape {tt.shape}, {tt.numElements} elements\n" &
               &"  {bufExpr(t)}\n\n"

  nimSrc.add "proc invoke*() =\n"
  nimSrc.add "  ## Straight-line execution. No interpreter, no dispatch table.\n"
  if opCalls.len == 0:
    nimSrc.add "  discard\n"
  else:
    nimSrc.add opCalls

  var hdr, src: string
  emitWeightsFiles(g, blobs, stem, hdr, src)

  writeFile(outDir / (stem & "_weights.h"), hdr)
  writeFile(outDir / (stem & "_weights.c"), src)
  writeFile(outDir / (stem & ".nim"), nimSrc)
